# Runs the tests against an non-emulated Firebase RTDB

tags:
  - firebase-database-pagination
  - integration-tests
  - single-build

options:
  env:
    - FIREBASE_DB_NAME=${PROJECT_ID}-${_FIREBASE_DB_NAME}

# Don't use waitFor so tests are all run sequentially and don't causes failures due to duplicate data writes
steps:
  - id: node14-test
    name: node:14-alpine
    entrypoint: yarn
    args:
      - int-test

  - id: node16-test
    name: node:16-alpine
    entrypoint: yarn
    args:
      - int-test
