# Runs the tests against an non-emulated Firebase RTDB

tags:
  - firebase-database-pagination
  - integration-tests
  - single-build

options:
  env:
    - FIREBASE_DB_NAME=${PROJECT_ID}-${_FIREBASE_DB_NAME}

# Don't use waitFor so tests are all run sequentially and don't causes failures due to duplicate data writes
steps:
  - id: node20-test
    name: node:20-alpine
    entrypoint: npm
    args:
      - run
      - int-test

  - id: node22-test
    name: node:22-alpine
    entrypoint: npm
    args:
      - run
      - int-test
